---
chapter: 비동기 제어
title: Promise
date: 2024-11-18
---

## 2.1 Promise란?

Promise는 이름에서 알 수 있듯이 ‘약속’을 의미하는 자바스크립트 객체입니다. 비동기 작업의 최종 결과 또는 실패를 처리할 수 있도록 상태를 알려주겠다는 약속을 하는 객체를 만들 수 있습니다.

Promise는 3가지 상태를 가지며, 응답에 따라서 상태가 변경됩니다.

1. 대기(Pending): 초기 상태로 로직이 **완료되지 않은** 상태
2. 이행(Fulfilled): 비동기 처리를 **성공적으로 완료**된 상태, 처리 결과 값을 반환
3. 거부(Rejected): 처리가 **실패했거나 오류**가 발생한 상태

Promise 객체를 생성하기 위해서는 생성자 함수를 사용합니다. 객체를 생성할 때 함수를 인자로 전달받습니다. 이 함수를 executor라고 부릅니다. 이 executor 함수는 두 개의 함수를 인자로 전달받는데, 관습적으로 resolve, reject라고 부릅니다.

```jsx
const promise = new Promise((resolve, reject) => {});
```

resolve 함수는 Promise가 성공적으로 완료되었을 때 호출되고, 이행(fulfilled) 상태로 변경합니다. 반대로 reject 함수는 작업이 실패했을 때 호출되며, 거부(rejected) 상태로 변경합니다.

- 대기(pending) → resolve → 이행(fulfilled)

```jsx
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('요청 성공');
  }, 1000);
});

promise.then((response) => {
  console.log(response);
});
```

- 대기(Pending) -> reject -> 거부(Rejected)

```jsx
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject(new Error('요청 실패')); // 오류 객체
  }, 1000);
});

promise.catch((error) => {
  console.error(error);
});
```

## 2.2 Promise의 메서드

### 2.2.1 then

- Promise가 **이행되거나** 거부되었을 때 실행될 콜백 함수

```jsx
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('요청 성공');
  }, 1000);
});

promise.then((response) => {
  console.log(response);
});
```

:::div{.callout}

**then의 반환값에 따른 Promise 형태**

1. 값을 그대로 반환 (또는 반환값이 없을 때)

   ```jsx
   promise
     .then((response) => {
       return 'Hello World';
     }) // Promise.resolve("Hello World")와 동일
     .then((result) => {
       console.log(result);
     });
   ```

1. Promise를 반환

   ```jsx
   promise
     .then((response) => {
       return new Promise(function (resolve, reject) {
         setTimeout(() => {
           resolve('Hello World');
         }, 1000);
       });
     })
     .then((result) => {
       console.log(result);
     });
   ```

:::

### 2.2.2 catch

- Promise가 거부되었을 때 실행될 콜백 함수
- `.then(null, onRejected)`와 같은 역할

```jsx
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    reject(new Error('요청 실패')); // 오류 객체
  }, 1000);
});

promise.catch((error) => {
  console.error(error);
});
```

### 2.2.3 finally

- Promise의 이행 또는 거부 여부와 관계없이 실행될 콜백 함수

```jsx
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('요청 성공');
  }, 1000);
});

promise
  .then((response) => {
    console.log(response);
  })
  .catch((error) => {
    console.error(error);
  })
  .finally(() => {
    console.log('프로미스 종료!');
  });
```

:::div{.callout}

**Promise의 메서드 체이닝**

Promise에서 제공하는 then(), catch(), finally() 메서드는 새로운 Promise를 반환합니다. 따라서 메서드 체이닝이 가능합니다. 일반적으로 다음과 같은 구조로 메서드를 연결하여 사용합니다.

```jsx
promise
  .then((response) => {
    console.log(response);
  })
  .catch((error) => {
    console.error(error);
  })
  .finally(() => {
    console.log('프로미스 종료!');
  });
```

:::
